//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string Balance { get; set; }
        public string Amount { get; set; }
        public string Transfer_Amount { get; set; }
        public string Charges { get; set; }
        public string Debit_Amount { get; set; }
    }
}
